name: "SonarQube Implementation with Github Actions for dissertatio"

on:
  push:
    branches:
      - Newbranch
  pull_request:
    branches:
      - Newbranch

jobs:
  build-and-analyze:
    name: Build, Test, and Analyze
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: Set up Node
      uses: actions/setup-node@v3
      with:
        node-version: 'latest'

    - name: Install dependencies
      run: npm install

    - name: Run OWASP Juice Shop tests
      run: npm test

    - name: Set up SonarQube Scanner
      uses: sonarsource/sonarcloud-github-action@v3
      with:
        sonar-token: ${{ secrets.SONARQUBE_TOKEN }}

    - name: Run SonarQube analysis
      run: |
        npm install -g sonar-scanner
        sonar-scanner \
          -Dsonar.projectKey=your-project-key \
          -Dsonar.sources=. \
          -Dsonar.host.url=https://your-sonarqube-server \
          -Dsonar.login=${{ secrets.SONARQUBE_TOKEN }}
      env:
        SONARQUBE_TOKEN: ${{ secrets.SONARQUBE_TOKEN }}
