name: SonarQube Implementation with Github Actionss

on:
  push:
    branches:
      - Newbranch
  pull_request:
    branches:
      - Newbranch

jobs:
  build-and-analyze:
    name: Build, Test, and Analyze
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v4.1.0
      with:
        node-version: 'latest'

    - name: Install dependencies
      run: npm install

    - name: Run OWASP Juice Shop tests
      run: npm test

    - name: Set up SonarQube Scanner
      uses: sonarsource/sonarcloud-github-action@v2
      with:
        sonar-token: ${{ secrets.SONARQUBE_TOKEN }}
