name: ZAP-Scan 

on:
  push: 
    branches: [ Newbranch ]

jobs:
  zap_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: List files in the current directory
        run: ls -R

      - name: Run OWASP ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.13.0
        with:
          target: "https://juice-shop.herokuapp.com/#/" 
          cmd_options: "-t https://juice-shop.herokuapp.com/#/ -r report.html"

      - name: Upload ZAP report
        uses: actions/upload-artifact@v3
        with:
          name: ZAP Report
          path: report.html


